# Generated by Django 4.2.5 on 2023-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('n', 'not yet'), ('d', 'done')], max_length=15, verbose_name='Status'),
        ),
    ]
