# Generated by Django 4.2.5 on 2023-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('d', 'done'), ('a', 'active'), ('n', 'not yet')], max_length=15, verbose_name='Status'),
        ),
    ]
