# Generated by Django 4.2.5 on 2023-09-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='end_time',
            field=models.DateField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='start_time',
            field=models.DateField(verbose_name='Start time'),
        ),
    ]
